# Fritz!Box Spectrum Logger (https://github.com/c-mueller/fritzbox-spectrum-logger).
# Copyright (c) 2018 Christian MÃ¼ller <cmueller.dev@gmail.com>.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

[[constraint]]
  name = "github.com/caarlos0/env"
  version = "v3.2.0"

[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "v1.3.1"

[[constraint]]
  name = "github.com/fogleman/gg"
  version = "v1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  name = "gopkg.in/op/go-logging.v1"
  version = "1.0.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/dustin/go-humanize"

[[constraint]]
  name = "gopkg.in/cheggaaa/pb.v1"
  version = "1.0.25"
